### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by linakherchi** [estanob/588PX#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by linakherchi** [comment]
Great job ! 

Need to add description of the app at the top of your design doc.

Thanks

**Comment by linakherchi** [comment]
Please move the description you had in your Wiki Home Page in your MVP List. Thanks !

**Comment by linakherchi** [comment]
Hi Brandon ! Could you also please add a bullet point in your third MVP (post pictures) that expands on galleries ? ( Allowing users to add pictures to galleries ?) 

Are galleries going to be required or are you thinking of allowing the user to add pictures without these necessarily belong to a gallery ? 

Happy to chat further ! 

Thanks

**Comment by estanob** [comment]
Hi Lina! That's what I was thinking!
Users can add pictures to galleries, but it's not necessary for a picture to belong to a gallery
