### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by linakherchi** [estanob/588PX#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
Thanks, Brandon ! 

Could you explain the column `gallery_id` in the users table ? 

Thanks

**Comment by linakherchi** [comment]
Please also update the representation of your schema according to the above checklist. Thanks

**Comment by estanob** [comment]
Hi Lina, 
I realized that there was no need for `gallery_id` in the users table because a user could create multiple galleries, so there would be no need to assign gallery id.
I've already removed it from the users table!

**Comment by estanob** [comment]
Hi Lina, I have updated the schema and added the joins table for pictures in galleries
